#!/bin/bash

# Helper function
function dotfiles {
   /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

git clone --bare git@github.com:sebkinne/dotfiles.git $HOME/.dotfiles
dotfiles config status.showUntrackedFiles no

mkdir -p .dotfiles-backup

dotfiles checkout
if [ $? -ne 0 ]; then
    echo "Backing up pre-existing dotfiles.";
    dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi;

dotfiles checkout
